blackboard/urls.py
from django.contrib import admin
from blackboard import views
from django.urls import path, include
import random

app_name = 'room'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('room.urls')),
    path('', views.IndexView, name='home'),
]

room/urls.py
from django.urls import path
from room import views
import random

app_name = 'room'
random = random.randint(0, 9999)

urlpatterns = [
    path('<int:pk>/', views.Home, name='index'),
    path('create', views.create, name='create'),
    path('<int:pk>/changename', views.changename, name='changename'),
    path('<int:pk>/draw', views.draw, name='draw'),
    path('<int:pk>/reset', views.reset, name='reset'),
]

room/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
import json


class room(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.pk) + '_' + self.name


class line(models.Model):
    DoesNotExist = None
    points = models.TextField()
    c = models.IntegerField()
    w = models.IntegerField()
    t = models.IntegerField()
    draw = models.ForeignKey(room, on_delete=models.CASCADE)

    def __str__(self):
        return json.dumps({'point': self.points, 'c': self.c, 'w': self.w, 't': self.t})

blackboard/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from room.models import room
from django.views import generic


def IndexView(request):
    return render(request, 'home.html')

room/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from room.models import line, room
from django.views import generic
import json


def Home(request, pk):
    try:
        r = room.objects.get(pk=pk)
    except:
        return HttpResponseRedirect(reverse('home') + '?state=404')

    return render(request, 'room/main.html', {'r': r, 'socketid': pk})


def create(request):
    try:
        cnt = len(room.objects.all()) + 1
    except:
        cnt = 1

    while True:
        try:
            room.objects.get(pk=cnt)
        except:
            break
        cnt = cnt + 1
    try:
        room.objects.get(pk=cnt)
    except:
        room.objects.create(name='새 블랙보드', pk=cnt)

    return HttpResponseRedirect(reverse('room:index', args=(cnt,)))


@csrf_exempt
def changename(request, pk):
    try:
        r = room.objects.get(pk=pk)
        r.name = request.body.decode('utf-8')
        r.save()
    except:
        pass

    return HttpResponse()


@csrf_exempt
def draw(request, pk):
    try:
        el = json.loads(request.body)
        line.objects.create(points=el['point'], c=el['c'], w=el['w'], t=el['t'], draw=room.objects.get(pk=pk))
        return HttpResponse(1)
    except:
        return HttpResponse(0)


@csrf_exempt
def reset(request, pk):
    try:
        r = room.objects.get(pk=pk)
        for i in r.line_set.all():
            i.delete()
        return HttpResponse(1)
    except:
        return HttpResponse(0)

blackboard/templates/home.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>BlackBoard</title>
    {% load static %}
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <link href="https://unpkg.com/material-components-web@8.0.0/dist/material-components-web.min.css"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@8.0.0/dist/material-components-web.min.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <meta content="width=device-width, initial-scale=1" name="viewport">
</head>
<body>
<aside class="mdc-drawer mdc-drawer--modal">
    <div class="mdc-drawer__content">
        <nav class="mdc-list">
            <a class="mdc-list-item" href="{% url 'home' %}" aria-current="page" tabindex="0">
                <span class="mdc-list-item__ripple"></span>
                <i class="material-icons mdc-list-item__graphic" aria-hidden="true">inbox</i>
                <span class="mdc-list-item__text">메인</span>
            </a>
            <a class="mdc-list-item" href="{% url 'room:create' %}">
                <span class="mdc-list-item__ripple"></span>
                <i class="material-icons mdc-list-item__graphic" aria-hidden="true">send</i>
                <span class="mdc-list-item__text">새 블랙보드 만들기</span>
            </a>
        </nav>
    </div>
</aside>
<div class="mdc-drawer-scrim"></div>
<header class="mdc-top-app-bar mdc-top-app-bar--dense">
    <div class="mdc-top-app-bar__row">
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <button aria-label="Open navigation menu" onclick="drawer.open=true"
                    class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button" tabindex="0">menu
            </button>
            <a id="logo-a" href="{% url 'home' %}"><img id="logo" src="{% static 'res/logo_white.png' %}"></a>
            <span class="mdc-top-app-bar__title" id="title">BlackBoard</span>
        </section>
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar"></section>
    </div>
</header>
<main>
    <div>
        <a href="{% url 'room:create' %}">
            <div class="card"
                 style="background: url({% static 'res/back1.png' %});background-repeat: no-repeat;text-align: right;margin:50px;width:calc(50% - 160px);float:left;">
                <h1>새 블랙보드 만들기</h1>
                <p>새로운 공유 블랙보드를 만드세요!</p>
            </div>
        </a>
        <a onclick="shareDialog.open()">
            <div class="card"
                 style="background: url({% static 'res/back1.png' %});background-repeat: no-repeat;text-align: right;margin:50px;width:calc(50% - 160px);float:left;cursor: pointer;">
                <h1>다른 블랙보드에 참여하기</h1>
                <p>공유 블랙보드에 참여하세요!</p>
            </div>
        </a>
    </div>
    <h1>최근 연 블랙보드</h1>
    <div id="recent"></div>
    <p id="no-blackboard">최근 연 블랙보드가 없어요!</p>
</main>
<div class="mdc-dialog" id="share-dialog">
    <div class="mdc-dialog__container">
        <div aria-describedby="my-dialog-content"
             aria-labelledby="my-dialog-title"
             aria-modal="true"
             class="mdc-dialog__surface"
             role="alertdialog">
            <div class="mdc-dialog__content" id="my-dialog-content">
                <br>
                <h1>공유하기</h1>
                <p>참여할 블랙보드의 ID를 입력하세요!</p>
                <br>
                <div class="text-container">
                    <label class="mdc-text-field mdc-text-field--outlined" style="width: 100%;">
                  <span class="mdc-notched-outline">
                        <span class="mdc-notched-outline__leading"></span>
                        <span class="mdc-notched-outline__notch">
                          <span class="mdc-floating-label">링크</span>
                        </span>
                        <span class="mdc-notched-outline__trailing"></span>
                  </span>
                        <input aria-labelledby="my-label-id" class="mdc-text-field__input" id="shareUrl" type="text">
                    </label>
                </div>
            </div>
            <div class="mdc-dialog__actions">
                <button class="mdc-button mdc-dialog__button ripple" data-mdc-dialog-action="cancel" type="button"
                        onclick="join()">
                    <div class="mdc-button__ripple"></div>
                    <span class="mdc-button__label">참여</span>
                </button>
            </div>
        </div>
    </div>
    <div class="mdc-dialog__scrim"></div>
</div>
<div class="mdc-snackbar" id="snackbar">
    <div aria-relevant="additions" class="mdc-snackbar__surface" role="status">
        <div aria-atomic="false" class="mdc-snackbar__label" id="snackbar-text"></div>
        <div aria-atomic="true" class="mdc-snackbar__actions">
            <button class="mdc-button mdc-snackbar__action ripple" type="button">
                <div class="mdc-button__ripple"></div>
                <span class="mdc-button__label" style="color: var(--mdc-theme-primary) !important;">닫기</span>
            </button>
        </div>
    </div>
</div>
</body>
</html>

room/templates/room/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>BlackBoard</title>
    <script>
        let pointLi, socketId =
        {{ socketid }}
        try {
            pointLi = [{% for li in r.line_set.all %}{{ li|safe }}, {% endfor %}]
        } catch (e) {
            pointLi = []
        }
    </script>
    {% load static %}
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="https://unpkg.com/material-components-web@8.0.0/dist/material-components-web.min.css"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@8.0.0/dist/material-components-web.min.js"></script>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <script src="{% static 'js/canvas.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/color2filter.js' %}"></script>
</head>
<body>
<aside class="mdc-drawer mdc-drawer--modal">
    <div class="mdc-drawer__content">
        <nav class="mdc-list">
            <a class="mdc-list-item" href="{% url 'home' %}" aria-current="page" tabindex="0">
                <span class="mdc-list-item__ripple"></span>
                <i class="material-icons mdc-list-item__graphic" aria-hidden="true">inbox</i>
                <span class="mdc-list-item__text">메인</span>
            </a>
            <a class="mdc-list-item" href="{% url 'room:create' %}">
                <span class="mdc-list-item__ripple"></span>
                <i class="material-icons mdc-list-item__graphic" aria-hidden="true">send</i>
                <span class="mdc-list-item__text">새 블랙보드 만들기</span>
            </a>
        </nav>
    </div>
</aside>
<div class="mdc-drawer-scrim"></div>
<header class="mdc-top-app-bar mdc-top-app-bar--dense">
    <div class="mdc-top-app-bar__row">
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <button aria-label="Open navigation menu" onclick="drawer.open=true"
                    class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button">menu
            </button>
            <a id="logo-a" href="{% url 'home' %}"><img id="logo" src="{% static 'res/logo_white.png' %}"></a>
            <span class="mdc-top-app-bar__title" id="title"></span>
            <input id="title-input" style="display: none" type="text" value="{{ r.name }}">
        </section>
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
            <button aria-label="Sync Finished" class="material-icons mdc-top-app-bar__action-item mdc-icon-button"
                    id="synced">cloud_done
            </button>
            <svg class="spinner" width="65px" height="65px" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg"
                 id="syncing">
                <circle class="circle" fill="none" stroke-width="6" stroke-linecap="round" cx="33" cy="33"
                        r="10"></circle>
            </svg>
            <button aria-label="Share" class="material-icons mdc-top-app-bar__action-item mdc-icon-button"
                    onclick="share()">share
            </button>
            <button aria-label="Options"
                    class="material-icons mdc-top-app-bar__action-item mdc-icon-button mdc-menu-surface--anchor"
                    onclick="menu.open = true">more_vert
                <div class="mdc-menu mdc-menu-surface">
                    <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical" tabindex="-1">
                        <li class="mdc-list-item" role="menuitem" onclick="resetDialog.open()">
                            <span class="mdc-list-item__ripple"></span>
                            <span class="mdc-list-item__text">이 블랙보드 초기화</span>
                        </li>
                        <li class="mdc-list-item" role="menuitem" onclick="infoDialog.open()">
                            <span class="mdc-list-item__ripple"></span>
                            <span class="mdc-list-item__text">정보</span>
                        </li>
                    </ul>
                </div>
            </button>
        </section>
    </div>
</header>
<canvas id="drawCanv"></canvas>
<canvas id="mainCanv"></canvas>
<div class="closed" id="controls">
    <div id="control-container">
        <div class="pen" id="pen" onclick="selectPen(0)"></div>
        <div class="pen" id="marker" onclick="selectPen(1)"></div>
        <div class="pen" id="eraser" onclick="selectPen(2)"></div>
        <div id="thick">
            <div id="thick-container">
                <div onclick="selectThick(0)" style="width:10px;height: 10px;"></div>
                <div onclick="selectThick(1)" style="width:13px;height: 13px;"></div>
                <div onclick="selectThick(2)" style="width:15px;height: 15px;"></div>
                <div onclick="selectThick(3)" style="width:20px;height: 20px;"></div>
            </div>
        </div>
        <div id="color">
            <div id="color-container">
                <div onclick="selectColor(0)" style="background: #000000;border-color: #000000;"></div>
                <div onclick="selectColor(1)" style="background: #f55d49;border-color: #f55d49;"></div>
                <div onclick="selectColor(2)" style="background: #f5b049;border-color: #f5b049;"></div>
                <div onclick="selectColor(3)" style="background: #ede96f;border-color: #ede96f;"></div>
                <div onclick="selectColor(4)" style="background: #85e68a;border-color: #85e68a;"></div>
                <div onclick="selectColor(5)" style="background: #87d9ed;border-color: #87d9ed;"></div>
                <div onclick="selectColor(6)" style="background: #4d5ce3;border-color: #4d5ce3;"></div>
                <div onclick="selectColor(7)" style="background: #b96fed;border-color: #b96fed;"></div>
                <div onclick="selectColor(8)" style="background: #8a8a8a;border-color: #8a8a8a;"></div>
            </div>
        </div>
    </div>
</div>


<div class="mdc-dialog" id="share-dialog">
    <div class="mdc-dialog__container">
        <div aria-describedby="my-dialog-content"
             aria-labelledby="my-dialog-title"
             aria-modal="true"
             class="mdc-dialog__surface"
             role="alertdialog">
            <div class="mdc-dialog__content" id="my-dialog-content">
                <br>
                <h1>공유하기</h1>
                <p>아래 링크로 들어가면 공동 작업을 시작할 수 있어요!</p>
                <br>
                <div class="text-container">
                    <label class="mdc-text-field mdc-text-field--outlined" style="width: 100%;">
                  <span class="mdc-notched-outline">
                        <span class="mdc-notched-outline__leading"></span>
                        <span class="mdc-notched-outline__notch">
                          <span class="mdc-floating-label">링크</span>
                        </span>
                        <span class="mdc-notched-outline__trailing"></span>
                  </span>
                        <input aria-labelledby="my-label-id" class="mdc-text-field__input" id="shareUrl" type="text">
                    </label>
                </div>
                <br>
                <p>또는 아래 코드를 메인에서 입력하세요!</p>
                <h1>{{ socketid }}</h1>
            </div>
            <div class="mdc-dialog__actions">
                <button class="mdc-button mdc-dialog__button ripple" data-mdc-dialog-action="cancel" type="button">
                    <div class="mdc-button__ripple"></div>
                    <span class="mdc-button__label">닫기</span>
                </button>
                <button class="mdc-button mdc-dialog__button ripple" onclick="copyShareUrl()" type="button">
                    <div class="mdc-button__ripple"></div>
                    <span class="mdc-button__label">복사</span>
                </button>
            </div>
        </div>
    </div>
    <div class="mdc-dialog__scrim"></div>
</div>
<div class="mdc-dialog" id="info-dialog">
    <div class="mdc-dialog__container">
        <div aria-describedby="my-dialog-content"
             aria-labelledby="my-dialog-title"
             aria-modal="true"
             class="mdc-dialog__surface"
             role="alertdialog">
            <div class="mdc-dialog__content" id="my-dialog-content">
                <img src="{% static 'res/logo.png' %}" width="100">
                <h1>Blackboard</h1>
                <p>2020 인천과학예술영재학교 심우용, 유선혜, 이서현. All right reserved.</p>
            </div>
            <div class="mdc-dialog__actions">
                <button class="mdc-button mdc-dialog__button ripple" data-mdc-dialog-action="cancel" type="button">
                    <div class="mdc-button__ripple"></div>
                    <span class="mdc-button__label">닫기</span>
                </button>
            </div>
        </div>
    </div>
    <div class="mdc-dialog__scrim"></div>
</div>
<div class="mdc-dialog" id="reset-dialog">
    <div class="mdc-dialog__container">
        <div aria-describedby="my-dialog-content"
             aria-labelledby="my-dialog-title"
             aria-modal="true"
             class="mdc-dialog__surface"
             role="alertdialog">
            <div class="mdc-dialog__content" id="my-dialog-content">
                <br>
                <h1>정말 초기화할까요?</h1>
                <p>모든 내용이 사라집니다!</p>
            </div>
            <div class="mdc-dialog__actions">
                <button class="mdc-button mdc-dialog__button ripple" onclick="reset()" type="button">
                    <div class="mdc-button__ripple"></div>
                    <span class="mdc-button__label">초기화</span>
                </button>
                <button class="mdc-button mdc-dialog__button ripple" data-mdc-dialog-action="cancel" type="button">
                    <div class="mdc-button__ripple"></div>
                    <span class="mdc-button__label">취소</span>
                </button>
            </div>
        </div>
    </div>
    <div class="mdc-dialog__scrim"></div>
</div>
<div class="mdc-snackbar" id="snackbar">
    <div aria-relevant="additions" class="mdc-snackbar__surface" role="status">
        <div aria-atomic="false" class="mdc-snackbar__label" id="snackbar-text"></div>
        <div aria-atomic="true" class="mdc-snackbar__actions">
            <button class="mdc-button mdc-snackbar__action ripple" type="button">
                <div class="mdc-button__ripple"></div>
                <span class="mdc-button__label" style="color: var(--mdc-theme-primary) !important;">닫기</span>
            </button>
        </div>
    </div>
</div>
</body>
</html>